### ISSUE TITLE
Cambio de Etiqueta

### ISSUE THREAD

**Issue by amilianm** [BachacoVE/codegen-odoo#3]
Se cambia la etiqueta openerp por odoo en la vista del módulo

**Comment by amilianm** [comment]
Se cambia el nombre del archivo __openerp__.py a  __manifest__.py

**Comment by vijoin** [comment]
Es un Issue por cada cosa que quieras modificar...
y los comentarios son la discusión propia de cada Issue

**Comment by vijoin** [comment]
Este Issue ya fue resuelto?

**Comment by vijoin** [comment]
Ya hice el merge con estos cambios... 
commits ef85fca9e571601a715cf3e937b7d8c2e78a0aa5 y e597c4dce3879db9dec1150db4ec833d87f6d104
